import { SoundSource } from "../../hooks/useSound";

export const soundMapping: Record<SoundSource, string> = {
  menuItem: "button-click.mp3",
  menuButton: "button-click.mp3",
  soundVolume: "button-click.mp3",
  launchButton: "button-click.mp3",
  modeSelector: "button-click.mp3",
  characterSelector: "button-click.mp3",
  batButton: "button-click.mp3",
  pitchButton: "button-click.mp3",
  viewSelector: "button-click.mp3",
  cancelButton: "button-click.mp3",
  createButton: "button-click.mp3",
  imageSelector: "button-click.mp3",
  addCharacter: "button-click.mp3",
  pitchHistoryOpen: "button-click.mp3",
  pitchHistoryClose: "button-click.mp3",
  grid: "button-click.mp3",
  typeSelector: "button-click.mp3",
  heatmapClick: "button-click.mp3",
  commitButton: "button-click.mp3",
  homeButton: "button-click.mp3",
  loss: "loss.mp3",
  win: "win.mp3",
  heartbeat: "heartbeat.mp3",
  stadium: "stadium.mp3",
  contactHit: "",
  powerHit: "",
  walk: "",
  catch: "",
  error: "error.mp3",
  notification: "notification.mp3",
};
